### ISSUE TITLE
Getting Status 403 when "Collect Build Info" is not "true"

### ISSUE THREAD

**Issue by chrizzo84** [jfrog/artifactory-vsts-extension#111]
Hey guys,
we are getting a 403 on the generic upload task in Azure Pipelines if we don´t se "Collect Build Info"

Log:

Starting: Generic upload

Task         : Artifactory Generic Upload

Description  : Upload build artifacts to Artifactory using FileSpecs while allowing to collect build-

info. The collected build-info can be later published to Artifactory by the "Artifactory Publish Build 

Info" task.

Version      : 1.7.4

Author       : JFrog
Help         : 

Found tool in cache: jfrog 1.30.3 x64
Running jfrog-cli from d:\a\_tool\jfrog\1.30.3\x64\jfrog.exe.
JFrog CLI version: 1.30.3
Using file spec:
{
  "files": [
    {
           "pattern": "d:\\a\\1\\a/xxxx.zip",
           "target": "xxxxx"
    }
  ]
}
[Info] [Thread 2] Uploading artifact: d:\a\1\a\xxxx.zip
[Error] [Thread 2] Artifactory response: 403 Forbidden
{
  "status": "failure",
{
  "totals": {
  "errors": [
    "success": 0,
    {
    "failure": 1
      "status": 403,
  }
      "message": ""
}
    }
  ]
}
[Error] Failed uploading 1 artifacts.
##[error]Error: Command failed: d:\a\_tool\jfrog\1.30.3\x64\jfrog.exe rt u --url="https://xxxx" --spec="d:\a\1\s\uploadSpec1573232531243.json" --user=*** --password=*** --fail-no-op=true
Finishing: Generic upload

**Comment by eyalbe4** [comment]
@chrizzo84,
We've just tried reproducing this, and it seems to be working for us.
Few questions:

1. We assume that you masked the target in the file spec as "xxxxx". If so, can you please share with us the complete file spec you used? Please send us the spec text as you saved it in the UI and not the spec as it appears in the log. This may provide us with a hint to the cause of this issue. 
2. Is the file uploaded successfully when setting the *Collect build info* checkbox to on? Nothing is the task configuration is changed besides this?

Thanks

**Comment by eyalbe4** [comment]
@chrizzo84,
Adding the previous questions, one of the reasons for a *403 Forbidden* response can be received, is a wrong target repository name. Does the target repository configured exist and is it accessible for the user used?

**Comment by Chimera96** [comment]
@eyalbe4,
1. File spec in UI:
 {
  "files": [
    {
           "pattern": "$(Build.ArtifactStagingDirectory)/dist-$(version).zip",
           "target": "supplier-portal-food-generic/EXS/"
    }
  ]
}

2. Yes, the file is successfully uploaded when 'Collect build info' is selected and nothing in the task configuration is changed besides this.

Hope this helps.

**Comment by Chimera96** [comment]
@eyalbe4,
The target repository definitely exists. As mentioned just the 'Collect build info' is selected to get it working.

**Comment by yahavi** [comment]
@Chimera96,
As @eyalbe4, we couldn't reproduce the issue.
We have, however, some thoughts. It will be helpful if you can provide us with the following details:
1. Are you using hosted agent or private agent? Can you please provide us with more information about the agent such as the OS version? Also, if you are using private agent, you can try to delete the tasks cache in `<agent_home>\_work\_tasks\Artifactory*`
2. By looking into the Artifactory's logs we can conclude the root cause of the 403 error. For example, if the repository does not exist, we can see in artifactory.log: `should be a repo request and does not match any repo key`. To see artifactory.log, follow the instructions [here](https://www.jfrog.com/confluence/display/RTF/Artifactory+Log+Files#ArtifactoryLogFiles-ViewingLogFilesfromtheUI).
3. What is your Artifactory's version?

Thanks.

**Comment by eyalbe4** [comment]
@Chimera96 and @hrizzo84,
Are you still experiencing this issue with the latest release?
