### ISSUE TITLE
Artifactory Generic Upload - Add a target to the filepicker ui

### ISSUE THREAD

**Issue by Bjego** [jfrog/artifactory-vsts-extension#56]
Hey guys,
in your deprecated "JfrogArtifactDeployer", I had the opportunity to set the "Target Repository" and the file picker.

I migrated to the new plugin and need to write such custom json file for uploading my artifacts to a target repository in artifactory. 

I think this is a retrogression to your old plugin.

**Comment by eyalbe4** [comment]
@Bjego,
I'm not sure we should combine both File Specs and a repository select box.
File Specs are the result of many historical requests to allow a flexible, yet easy way to maintain artifacts. 
Using them is the way to go because they allow:
Configuring file patterns to be download or downloaded, including the exclusion of specific files / patterns.
Filtering files by properties and builds.
Support dynamic upload targets by using place-holders.
Manage the File Specs in the source control and have the Artifactory Download task access it after it is downloaded.
