### ISSUE TITLE
Set Working Directory from Artifactory Generic Upload Task

### ISSUE THREAD

**Issue by andydkelly-ig** [jfrog/artifactory-vsts-extension#76]
I have discovered an issue when wanting to upload a Folder structure from the Artifactory Generic Upload Task from Azure DevOps. When choosing not to have a flat structure so you preserve the folder hierarchy, it adds the entire filesystem path to your repo in Artifactory which is untidy.

Using the following file spec returns the result below:

`{
  "files": [
    {
      "pattern": "C:\\agent\\_work\\3\\s\\Output\\build_agent_1_\\dqplus-help\\",
      "target": "docs-release-local/d3s-dq+/3.2.0/docs/",
      "flat": "false"
    }
  ]
}`

![image](https://user-images.githubusercontent.com/42772281/59363822-be769d00-8d2d-11e9-8288-956fd0aebdad.png)

See above - i actually wanted all my folders to be under a folder heading of **dqplus-help** but i have no way of setting this as the working directory. 

If i copy the exact commands from the log and run from the local Command Line on the build agent, i am able to set the working directory as **C:\\agent\\_work\\3\\s\\Output\\build_agent_1_** change the file spec slightly and get the exact result i want by running the following command:

`C:\agent\_work\_tool\jfrog\1.23.1\x64\jfrog.exe rt u --url="https://artifactory.companyname.com/artifactory" --spec="C:\temp\spec.json" --user=USERNAME --password=TOKEN --fail-no-op=true`

`{
  "files": [
    {
      "pattern": "dqplus-help\\*",
      "target": "docs-release-local/d3s-dq+/3.2.0/docs/",
      "flat": "false"
    }
  ]
}`

![image](https://user-images.githubusercontent.com/42772281/59364215-668c6600-8d2e-11e9-9e8c-508d2622d01b.png)

**Comment by barbelity** [comment]
@andydkelly-ig in order to achieve this result, you should use [placeholders](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UsingPlaceholders). Placeholders offer you much more flexibility in several operations (such as uploading), and I encourage you to read further in our documentation.

In the discussed case, I would change the file-spec to be:
`{ "files": [ { "pattern": "C:\\agent\\_work\\3\\s\\Output\\build_agent_1_\\dqplus-help\\(*)", "target": "docs-release-local/d3s-dq+/3.2.0/docs/dqplus-help/{1}", "flat": "false" } ] }`

Please update if it resolves your issue.

**Comment by eyalbe4** [comment]
@andydkelly-ig,
I'm closing this issue for now. Please let us know if you need further assistance with this.
